= Report on Test Event and Developers Forum XXXIX, June 12-14, 2017
:docnumber: 1704
:copyright-year: 2017
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2017-07-21
:published-date: 2017-07-21
:technical-committee: IOPTEST
:docfile: csd-report-ioptestevent-39.adoc
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is a global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The event was hosted by Tandem in Seattle, Washington on June 12-14, 2017

The interoperability test event and developers forum had a relatively small number of attendees. While this led to little actual testing we did spend our time discussing some of the intricate details of work that is in progress. 

In attendance were:

* Tandem (our hosts)
* Spherical Cow Group with Bedework 
* Eventable
* FastMail
* Ribose

There was discussion of how to deal with categorization for the new data model and representation being developed in TC-API. This led to an agreement on the value being a URI and that the actual details of what that represented was outside of the scope of the TC-API work. This will also lead to some changes in the new calendaring extensions for event publication draft. Additionally we looked at what it was necessary to add to the data model to successfully handle tasks. 

We spent some time working on the subscription upgrade specification to ensure this would work successfully with caching servers. There was some discussion on how to flag a deleted event.The eventual consensus was to define a new "Deleted" status. We also felt it was important to define a time-range query as that is probably a very frequent use of subscriptions - e.g. what events happen this week? The consensus was that we should use a HEAD request to discover the possible upgrades rather than an OPTIONS request.

We spent some time discussing various aspects of VCARD. There was a lot to be discussed around the exact meaning of the UID. The wording of the specifications suggest that it is associated with the actual entity — i.e. a human or a resource. Many of us thought that it should really be tied to a particular representation of that entity. Associated with that was the issue of who or what should merge cards that appear to represent the same entity. A number of us felt that no merge should be attempted - it is up to the consumer to decide if two vCards represent the same person. Perhaps UIs should consider adding the ability to explicitly link VCARDs representing the same person. There is probably further discussion to be had on this issue.
