= Report on CalConnect Test Event and Developers Forum XLII, June 4-6, 2018
:docnumber: 1804
:copyright-year: 2018
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2018-06-29T00:00:00Z
:published-date: 2018-06-29T00:00:00Z
:technical-committee: IOPTEST
:docfile: csd-report-ioptestevent-42.adoc
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf
:local-cache-only:
:data-uri-image:
:toc:
:stem:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The event was hosted by Jorte in Tokyo, Japan, June 4-8, 2018

In attendance for this interoperability event and developers forum were representatives from

* Spherical Cow Group
* FastMail
* Open-Xchange
* Ribose
* Jorte


Despite that small attendance we were all kept busy on a number of issues which required discussion and implementation.

Vpoll was being worked on by Robert Stepanek of FastMail in preparation for a presentation and demonstration in the conference.

We had further discussions on the new JSCalendar specification Robert is working on. As the specification nears completion there are some remaining issues. The description property and localization, client-side alarm handling amd attendee-specific sequencing. As ever there were discussions about various aspects of recurrences.

The new server side subscriptions specification was discussed and the Open-Xchange members carried out a preliminary implementation of the specification. This specification allows DAV clients to POST subscription requests to the server which then manages the synchronization of the data. Open-Xchange proposed some additions be added: a "refresh now" option for clients and persisting and signaling account errors to clients. These most likely will be added to the final specification.

We talked about the progress being made with the VObject and VCard work in preparation for presentations later in the week.

Apart from the larger issues above these meetings provided the opportunity for face-to-face in depth discussion on various topics.
