= Report on CalConnect Interoperability Test Event XXXV, January 11-13, 2016
:docnumber: 1604
:copyright-year: 2016
:language: en
:doctype: administrative
:edition: 1
:status: published
:revdate: 2016-02-17T00:00:00Z
:published-date: 2016-02-17T00:00:00Z
:technical-committee: IOPTEST
:docfile: csd-report-ioptestevent-35.adoc
:mn-document-class: csd
:mn-output-extensions: xml,html,pdf
:local-cache-only:
:data-uri-image:
:toc:
:stem:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives.

In particular the different approval criteria needed for the different types of
ISO documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.

== Report

The Calconnect interoperability event was hosted by AOL at their Palo Alto site on January 11th through the morning of the 13th.

While it was a smaller than usual event much valuable work took place. There was the usual mix of in-depth discussions and actual testing of implementations.

On the testing front there was:

* Work on the server-info document
* CalDav Tester
* Ralph Beckers caldav tester scripts
* General CalDAV

The server-info document is a new specification being developed to provide cacheable server information for use by clients, detailing services available and some limits. This has been implemented by a number of servers and some clients. Each interoperability event has led to changes in the specification. The general feeling is that it is now ready for wider testing and use.

The CalDAV tester is associated with Apple's Darwin open source server offering and provides many tests of CardDAV, CalDAV and related features. It is very configurable. Ralph Becker's tool helps to run the tests and store results.

While historically, this has been an event focusing on interoperability testing we have been moving towards having more in-depth, developer-centric discussions on topics of interest.

This event was no exception with discussions on all of the above topics as well as how best to move forward with the new developers guide.

We are looking forward to being back to our usual larger attendance at Hong Kong in April. Check the website over the coming weeks as we will be updating the schedule to reflect the specific interests of the attendees,